services:
  #PgSQL Service
  db:
    image: postgres:12
    environment:
      TZ: "Asia/Jakarta"
      POSTGRES_PASSWORD: "Password"
    restart: unless-stopped
    tty: true
    ports:
      - '54321:5432'
    volumes:
      - './psql:/var/lib/postgresql/data'